Error Check

diff --git a/.github/workflows/tf_gcp_pr_plan.yml b/.github/workflows/tf_gcp_pr_plan.yml
--- a/.github/workflows/tf_gcp_pr_plan.yml
+++ b/.github/workflows/tf_gcp_pr_plan.yml
@@ -2,6 +2,7 @@ name: Terraform PR Plan
 
 on:
   workflow_dispatch:    
+  push:
   pull_request:
     branches: 
       - main
@@ -41,7 +42,6 @@ jobs:
           echo "GCP_PROJECT_ID=$gcp_project" >> $GITHUB_ENV
           echo "ORG_ID=${{ secrets.ORG_ID }}" >> $GITHUB_ENV
           echo "HUB_TOKEN=${{ secrets.HUB_TOKEN }}" >> $GITHUB_ENV
-
       - name: Set up gcloud SDK environment
       # Helps to download gcloud SDK's into the runners machines
         uses: google-github-actions/setup-gcloud@v0
@@ -73,7 +73,6 @@ jobs:
         if: github.event_name == 'pull_request'
         run: |
           terraform plan -var-file ../env/${{ matrix.workspace }}.tfvars -input=false -lock=false -refresh=true -out=tfplan -no-color
-
       - name: Update Pull Request
         uses: actions/github-script@v6
         if: github.event_name == 'pull_request'
@@ -87,18 +86,13 @@ jobs:
             #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
             #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
             #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-
             <details>
               <summary>
                   Show Plan
               </summary>
-
             \`\`\`${process.env.PLAN}\`\`\`
-
             </details>
-
             *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-
             github.rest.issues.createComment({
               issue_number: context.issue.number,
               owner: context.repo.owner,
@@ -106,6 +100,24 @@ jobs:
               body: output
             })
       
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
+
+      # On push to master, build or change infrastructure according to Terraform configuration files
+      - name: Terraform Apply
+        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+        id: Apply
+        run: |
+          terraform apply -auto-approve -input=false -var-file ../env/${{ matrix.workspace }}.tfvars -lock=false -refresh=true
+          
+      
+      # On push to master, build or change infrastructure according to Terraform configuration files
+      # - name: Terraform Destroy
+      #   if: github.ref == 'refs/feature/destroy' && github.event_name == 'push'
+      #   run: terraform destroy -auto-approve -var-file ../env/${{ matrix.workspace }}.tfvars -input=false -lock=false -refresh=true
+
+
+      # pull --> Checksum --> merge / master --> apply github action --> Checksum value ( State tf )
+
+      # 3 -- Repo - Will call central repo's -- Copy module -- networking -- module 
