Configure Yaml

diff --git a/.github/workflows/tf_gcp.yml b/.github/workflows/tf_gcp.yml
--- a/.github/workflows/tf_gcp.yml
+++ b/.github/workflows/tf_gcp.yml
@@ -64,15 +64,15 @@ jobs:
         run: terraform validate -no-color
 
       - name: Terraform Plan GCP
-        if: github.event_name == 'pull_request'
         working-directory: ./gcp
         id: plan
+        if: github.event_name == 'pull_request'
         run: |
           terraform plan -var-file ../env/${{ matrix.workspace }}.tfvars -input=false -lock=false -refresh=true -no-color
 
       - name: Update Pull Request
         uses: actions/github-script@v6
-        if: github.event_name == 'pull_request'
+        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main' && github.event_name == 'push'
         env:
           PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
         with:
@@ -91,7 +91,7 @@ jobs:
 
             </details>
 
-            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`, Workflow: \`${{ github.workflow }}\`*`;
 
             github.rest.issues.createComment({
               issue_number: context.issue.number,
@@ -100,9 +100,9 @@ jobs:
               body: output
             })
       
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
 
       # On push to master, build or change infrastructure according to Terraform configuration files
       - name: Terraform Apply
